### ISSUE TITLE
Problem with fast successive ajax queries

### ISSUE THREAD

**Issue by olivierdalang** [nevimov/django-easycart#8]
Hi !

Using the provided views, if I send an ajax request to add an item, then another one before I got the first one, it seems the cart is overwritten by the last query, making the first item disappear from the cart.

I think this is caused because each requests creates a Cart instance, and each cart instance works on a different self.items and then reset the session variable at the end of processing.

**Comment by nevimov** [comment]
Hi, I think you should use JavaScript to ensure that you don't make new requests to the cart until you receive a response for the current one. Otherwise, you may encounter a whole lot of other issues besides the one you've mentioned. Generally, we cannot guarantee the order in which requests will
be processed by the server unless we use some help from client-side code.

**Comment by olivierdalang** [comment]
Yes but from an user point of view it's not that great if there's a lot of latency.

I think respecting order isn't expected, but it is expected that two successive "add" actions result in two added items, which currently isn't the case.

**Comment by nevimov** [comment]
Can you provide more info on how do you get the issue? How do you make these requests?
Are you clicking  the "Add" button on the first item, then "Add" button on the second item and after that only one of the items is added?

**Comment by olivierdalang** [comment]
Yes it's exactly like that. You can reproduce the problem easily if you add a sleep() call in your view.

**Comment by nevimov** [comment]
Well, such problem is expected with a sleep() call, but I'm surprised that you're running into this issue without it.  I'll look into it tomorrow.

**Comment by nevimov** [comment]
OK, here's my reasoning:

* What we have is a classical read-modify-write race condition. Several threads/processes read the session, modify it, then one overrides the other.

* One way to solve the issue would be to lock read-write access to the user's session while one of the cart views performs. Unfortunately, it looks like there's no *good* platform-independent way to do it.  For example, the `select_for_update()` queryset method doesn't work on all backends supported by Django, and requires changing the default  transaction isolation level to work (at least with PostgreSQL). Solutions I've found are either too complex or bring more problems than they solve (like deadlocks). It will be much more irritating for the user to end up with a non-working cart, than any latency issues.

* Also, as I mentioned before, there's still execution order problem, which will not be solved by the locking alone.  For example, let's suppose, a user adds an item in quantity X, then suddenly realizes that actually he needs Y units of the item, so he changes the value to Y.  Somehow, the server gets the requests almost simultaneously.  In this case, the quantity may be set to X, which is not the expected behavior. There's more similar examples, but I think the idea is clear.

* On the other hand, we have the browser, which allows us to implement an easier and
platform-independent solution for both of the problems described above.

I agree, though, that the current behavior is not obvious at all. At the moment, my best idea is to simply add a warning to the docs. If you have suggestions, I'm all ears :)
